// CARD ACTIONS
export const LIKE_TOGGLE = "LIKE_TOGGLE";
export const DISLIKE_TOGGLE = "DISLIKE_TOGGLE";
export const BOOKMARK_TOGGLE = "BOOKMARK_TOGGLE";

// HAMBURGER ACTIONS
export const HAMBURGER_TOGGLE = "HAMBURGER_TOGGLE";

// VISIBILITY_FILTER ACTIONS
export const SHOW_ALL = "SHOW_ALL";
export const SHOW_LIKED = "SHOW_LIKED";
export const SHOW_DISLIKED = "SHOW_DISLIKED";
export const SHOW_BOOKMARKED = "SHOW_BOOKMARKED";
